# Generated by Django 5.2.7 on 2025-10-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('category', models.CharField(choices=[('plush', 'Плюшевые'), ('edu', 'Обучающие'), ('electronic', 'Электронные'), ('puzzle', 'Пазлы'), ('outdoor', 'Уличные')], max_length=20, verbose_name='Категория')),
                ('size', models.CharField(choices=[('small', 'Маленький'), ('medium', 'Средний'), ('large', 'Большой')], max_length=10, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Игрушка',
                'verbose_name_plural': 'Игрушки',
            },
        ),
    ]
